import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const inputPath = path.join(here, 'sulfur-dioxide-template-extract.json');
const outputPath = path.join(here, '..', 'assets', 'sulfur-dioxide-templates.js');
const source = JSON.parse(fs.readFileSync(inputPath, 'utf8').replace(/^\uFEFF/, ''));

function cleanProduct(file) {
  let stem = file.replace(/\.docx?$/i, '').replace(/^\d+/, '').trim();
  const marker = /(?:原料|成品)?检验记(?:录)?/;
  const match = marker.exec(stem);
  if (!match) return stem.replace(/\s+/g, '');
  const base = stem.slice(0, match.index).trim().replace(/[.。]+$/g, '');
  let suffix = stem.slice(match.index + match[0].length).trim();
  suffix = suffix.replace(/\(\d+\)$/g, '').replace(/[123]$/g, '').trim();
  suffix = suffix.replace(/^[.。\-—_]+/, '').trim();
  return (base + suffix).replace(/\s+/g, '');
}

function baseProductOf(product) {
  let base = product;
  while (/(?:（[^（）]+）|\([^()]+\))$/.test(base)) {
    base = base.replace(/(?:（[^（）]+）|\([^()]+\))$/, '');
  }
  return base || product;
}

function fnv1a(text) {
  let hash = 0x811c9dc5;
  for (const ch of text) {
    hash ^= ch.codePointAt(0);
    hash = Math.imul(hash, 0x01000193);
  }
  return (hash >>> 0).toString(36);
}

function standardFromSection(section) {
  const lines = section.context || [];
  const formulaIndex = lines.findIndex(line => /0\.032.*10\s*6|0\.032.*106/.test(line));
  if (formulaIndex < 0 || !lines.some(line => /滴定液浓度|氢氧化钠滴定液/.test(line))) return '';
  for (let i = formulaIndex + 1; i < Math.min(lines.length, formulaIndex + 24); i++) {
    if (/标准规定/.test(lines[i]) && /mg\s*\/\s*kg/i.test(lines[i])) return lines[i];
  }
  return '';
}

function limitsFromStandard(standardText) {
  const text = standardText.replace(/\s+/g, ' ').replace(/ｍｇ/gi, 'mg').replace(/ｋｇ/gi, 'kg');
  const matches = [...text.matchAll(/([^，。；;]{0,36}?)(?:不得过|不得超过|不应超过)\s*([0-9]+(?:\.[0-9]+)?)\s*mg\s*\/\s*kg/gi)];
  const limits = matches.map(match => {
    let variant = match[1]
      .replace(/^.*(?:标准规定|通则2331|测定)[：:]?[，,]?/g, '')
      .split(/mg\s*\/\s*kg/i).pop()
      .replace(/^[，,、和及\s]+|[，,、和及\s]+$/g, '');
    if (/^(本品|二氧化硫残留量)$/.test(variant)) variant = '';
    return { limit: match[2], variant };
  });
  if (limits.length <= 1) return limits.map(limit => ({ ...limit, variant: '' }));
  return limits;
}

const candidates = [];
for (const record of source.records || []) {
  const product = cleanProduct(record.file);
  const baseProduct = baseProductOf(product);
  const kind = /原料检验/.test(record.file) ? '原料'
    : (/成品检验/.test(record.file) ? '成品' : record.kind);
  const standards = [...new Set((record.sections || []).map(standardFromSection).filter(Boolean))];
  for (const standardText of standards) {
    const limits = limitsFromStandard(standardText);
    // 多限度标准必须点名当前品种；例如个别复用表格残留了“山药片”的旧标准，
    // 不能将它错误套到射干等无关品种。
    if (limits.length > 1 && !limits.some(({ variant }) =>
      variant.includes(baseProduct) || baseProduct.includes(variant))) continue;
    for (const { limit, variant } of limits) {
      const key = [kind, product, variant, limit].join('|');
      candidates.push({
        id: `q-sulfur-${fnv1a(key)}`,
        item: 'sulfur',
        product,
        baseProduct,
        kind,
        variant,
        label: `${product}${variant ? `·${variant}` : ''}（${kind}）`,
        standardText: standardText.replace(/\s+/g, ' ').trim(),
        limop: 'le',
        limit,
        method: '照二氧化硫残留量测定法（通则2331）测定。',
        methodType: 'acid-base-titration',
        sourceFile: record.file,
        modified: record.modified || ''
      });
    }
  }
}

const unique = new Map();
for (const item of candidates) {
  const key = [item.kind, item.product, item.variant, item.limit].join('|');
  const previous = unique.get(key);
  if (!previous || item.modified > previous.modified) unique.set(key, item);
}

const templates = [...unique.values()]
  .sort((a, b) =>
    a.product.localeCompare(b.product, 'zh-CN') ||
    a.kind.localeCompare(b.kind, 'zh-CN') ||
    a.variant.localeCompare(b.variant, 'zh-CN') ||
    Number(a.limit) - Number(b.limit))
  .map(({ modified, ...item }) => item);
const records = new Set(templates.map(template => `${template.kind}|${template.sourceFile}`)).size;
const products = new Set(templates.map(template => template.baseProduct)).size;
const counts = {
  templates: templates.length,
  records,
  products,
  raw: templates.filter(template => template.kind === '原料').length,
  finished: templates.filter(template => template.kind === '成品').length
};

const output = [
  '/* Generated by tools/build_sulfur_dioxide_templates.mjs from local inspection records. */',
  `const SULFUR_DIOXIDE_TEMPLATES = ${JSON.stringify(templates)};`,
  `const SULFUR_DIOXIDE_TEMPLATE_COUNTS = ${JSON.stringify(counts)};`,
  ''
].join('\n');
fs.writeFileSync(outputPath, output, 'utf8');
console.log(JSON.stringify(counts, null, 2));
